"""Add billing fields

Revision ID: 98ccad51a572
Revises: e8fe9fd6c7e3
Create Date: 2026-04-28 20:34:33.578411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ccad51a572'
down_revision = 'e8fe9fd6c7e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_type', sa.String(length=20), server_default='free', nullable=False))
        batch_op.add_column(sa.Column('plan_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('razorpay_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('razorpay_subscription_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('razorpay_subscription_id')
        batch_op.drop_column('razorpay_customer_id')
        batch_op.drop_column('plan_expires_at')
        batch_op.drop_column('plan_type')

    # ### end Alembic commands ###
